#!/bin/bash

cat <<-EOF
{"timestamp": "$(date -u +"%Y-%m-%dT%H:%M:%S.%3NZ")", "level": "info", "message":  "ZITI_BROWZER_BOOTSTRAPPER_LOG_PATH is ${ZITI_BROWZER_BOOTSTRAPPER_LOG_PATH:-null}"}
EOF

if [ -z "$NODE_EXTRA_CA_CERTS" ]; then
	export NODE_EXTRA_CA_CERTS="node_modules/node_extra_ca_certs_mozilla_bundle/ca_bundle/ca_intermediate_root_bundle.pem"
    echo "NODE_EXTRA_CA_CERTS not set. using default: $NODE_EXTRA_CA_CERTS"
else
    echo "NODE_EXTRA_CA_CERTS configured to use: $NODE_EXTRA_CA_CERTS"
fi

if [ -z ${ZITI_BROWZER_BOOTSTRAPPER_LOG_PATH} ]; then
    exec node index.js
else
    exec node index.js >> "${ZITI_BROWZER_BOOTSTRAPPER_LOG_PATH}" 2>&1
fi