#!/bin/sh

# npx greenlock init --config-dir /ziti/greenlock.d --maintainer-email "$ZITI_AGENT_ACME_MAINTAINER_EMAIL"

npx greenlock add --subject "$ZITI_AGENT_HOST" --altnames "$ZITI_AGENT_HOST"

node index.js >> /ziti/log/ziti-http-agent.log 2>&1 &