#!/bin/bash

if [ -z ${ZITI_AGENT_LOG_PATH} ]; then
    echo "no ZITI_AGENT_LOG_PATH var was found"
    node index.js
else
    echo "the ZITI_AGENT_LOG_PATH var was found: '${ZITI_AGENT_LOG_PATH}'"
    node index.js >> "${ZITI_AGENT_LOG_PATH}" 2>&1
fi
