
name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      tags:
        required: false
        description: 'Misc tags'

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: ${{ github.run_number }}
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PAT }} 

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo `git branch --show-current`)"
        id: extract_branch

      - name: Build/Push (main)
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/openziti/ziti-http-agent:${{ github.run_number }}
            ghcr.io/openziti/ziti-http-agent:latest
        if: |
          steps.extract_branch.outputs.branch == 'main'

      - name: Build/Push (PR)
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/openziti/ziti-http-agent:${{ github.run_number }}
            ghcr.io/openziti/ziti-http-agent:snapshot-${{ steps.extract_branch.outputs.branch }}-${{ github.run_number }}
        if: |
          steps.extract_branch.outputs.branch != 'main'
          