name: Promote Image to Stable

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Image tag to promote to stable"
        required: true
  push:
    branches:
      - bootstrapper-issue-364

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PAT }} 

      - name: Retag image as stable
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/ziti-browzer-bootstrapper
          VERSION=${{ github.event.inputs.version }}

          # Pull the existing image
          docker pull $IMAGE_NAME:$VERSION

          # Retag it as "stable"
          docker tag $IMAGE_NAME:$VERSION $IMAGE_NAME:stable

          # Push both tags
          docker push $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:stable
